### ISSUE TITLE
Download statistic fails

### ISSUE THREAD

**Issue by mgambarara** [ethz-let/moodle-qtype_kprime#11] opened 2015-08-18 20:50 UTC
![download statistics in excel](https://cloud.githubusercontent.com/assets/12081367/9342296/35a5fa16-45fb-11e5-9940-ee72b2ef03a7.png)

Go to Results -> Statistics -> Excel spreadsheet

The error message in the attached file appears.

The error also appears in the productive course moodle.

**Comment by nexterday** [comment] 2015-08-18 21:22
What is the quiz and/or question title? Names with special characters do not export due to excels engine in moodle and not specifically to a question type..  (Some of the printable ASCII characters are invalid:  \* : / \ ? [ ] and  first and last characters cannot be a " ' ").

A) Check the quiz title/name and question title/name and see if they have special characters (: / \ ? [ ]  @ ' " etc)

B) To reproduce create quiz with same details and a different question type but with same details of this one and try to export - whats the result?

**Comment by mgambarara** [comment] 2015-08-20 00:50
Quiz title: KPrim Test
Question title: KPrim

b) The error also appeared with a multiple choice question type. 

While the retesting now I found out, that the download works when the moodle is on english. It does only not work when it's on german.

https://moodle-app1-skal.let.ethz.ch/mod/quiz/report.php?id=80093&mode=statistics

**Comment by isacsonk** [comment] 2015-08-20 12:21
Amr, I added you as a teacher in Marinos course, so that you can have a look.
One of the question titles is spelled with an ä (Umlaute), but there are no other special characters as far as I could tell. 
If the ä is making a problem; since we are in Switzerland, Umlaute will have to work, there will be Umlaute in question names for sure.

**Comment by nexterday** [comment] 2015-08-20 12:36
As you can see from comment above the issue is at moodle code - will dig into moodle and see if the matter can be fixed withiut tocuhing moodle core

**Comment by isacsonk** [comment] 2015-08-20 12:42
ok, if it is in moodle core, we will suggest the workaround to people to switch to english to download the information. 
If the matter can be fixed without touching moodle core, it would be great, as long as it doesn't take too much time too fix.

**Comment by nexterday** [comment] 2015-08-26 13:47
moodle core for german - not kprime, closing #11

**Closed as completed by nexterday** 2015-08-26 13:47 UTC
